import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./component/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="flex flex-col items-center h-screen">
        <Header />
          {children}
      </body>
    </html>
  );
}
